### PR TITLE
Improve terminal response line

### PR DESCRIPTION
**Pull request by rafaelcamargo**
Resolves https://github.com/glorious-codes/glorious-demo/issues/36

White spacing plain text responses with pre style.

**Preview**

### CODE REVIEW

**Comment by rafaelcamargo** [comment]
Hey @heowc and @mostafaebrahimi, could you give a look on this?

I was figuring out here which version I should set for this.
Only a patch  `0.7.1` or a major `1.0.0`? In practice, I am braking backwards compatibility, ain't I? 🤔

**Comment by mostafaebrahimi** [comment]
Hi @rafaelcamargo.
I think it's a patch and better to be `0.7.1` and you didn't breaking backward compatibility here.

**Comment by heowc** [comment]
I think it's a patch and better to be `0.7.1` too.

**Comment by rafaelcamargo** [comment]
Just released `v0.7.1` 🎉 
Thank you guys!

**Pull request merged**
